[project]
name = "mcptest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.4.1",
    "paramiko>=3.5.1",
    "psutil>=7.0.0",
]
